/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author HP
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
        
        KontenUtama.add(KaryawanPanel, "KaryawanPanel");
        KontenUtama.add(ProyekPanel, "ProyekPanel");
        KontenUtama.add(TransaksiPanel, "TransaksiPanel");
        
        listKaryawan();
        listProyek();
        listTransaksi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Navbar = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        Konten = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        navKaryawan = new javax.swing.JButton();
        navProyek = new javax.swing.JButton();
        navTransaksi = new javax.swing.JButton();
        KontenUtama = new javax.swing.JPanel();
        KaryawanPanel = new javax.swing.JPanel();
        FormKaryawanFrame = new javax.swing.JInternalFrame();
        jLabel4 = new javax.swing.JLabel();
        namaKaryawan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jabatanKaryawan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        departemenKaryawan = new javax.swing.JTextField();
        submitKaryawan = new javax.swing.JButton();
        titleFormKaryawan = new javax.swing.JLabel();
        errNamaKaryawan = new javax.swing.JLabel();
        errJabatanKaryawan = new javax.swing.JLabel();
        errDepartemenKaryawan = new javax.swing.JLabel();
        idFormKaryawan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Karyawan = new javax.swing.JTable();
        btn_addKaryawan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ProyekPanel = new javax.swing.JPanel();
        FormProyekFrame = new javax.swing.JInternalFrame();
        jLabel7 = new javax.swing.JLabel();
        namaProyek = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        durasiPengerjaan = new javax.swing.JTextField();
        submitProyek = new javax.swing.JButton();
        titleFormProyek = new javax.swing.JLabel();
        errNamaProyek = new javax.swing.JLabel();
        errDurasiPengerjaan = new javax.swing.JLabel();
        idFormProyek = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Proyek = new javax.swing.JTable();
        btn_addProyek = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        TransaksiPanel = new javax.swing.JPanel();
        FormTransaksiFrame = new javax.swing.JInternalFrame();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        submitTransaksi = new javax.swing.JButton();
        titleFormTransaksi = new javax.swing.JLabel();
        errDataKaryawan = new javax.swing.JLabel();
        errDataProyek = new javax.swing.JLabel();
        idFormTransaksi = new javax.swing.JLabel();
        DataKaryawanFormTransaksi = new javax.swing.JComboBox<>();
        DataProyekFormTransaksi = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        PeranFormTransaksi = new javax.swing.JTextField();
        errPeran = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_Transaksi = new javax.swing.JTable();
        btn_addTransaksi = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Navbar.setBackground(new java.awt.Color(51, 51, 51));

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("PT.Barokah");

        javax.swing.GroupLayout NavbarLayout = new javax.swing.GroupLayout(Navbar);
        Navbar.setLayout(NavbarLayout);
        NavbarLayout.setHorizontalGroup(
            NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavbarLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel12)
                .addContainerGap(852, Short.MAX_VALUE))
        );
        NavbarLayout.setVerticalGroup(
            NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Navbar, java.awt.BorderLayout.PAGE_START);

        Konten.setLayout(new javax.swing.BoxLayout(Konten, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        navKaryawan.setBackground(new java.awt.Color(51, 102, 255));
        navKaryawan.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        navKaryawan.setForeground(new java.awt.Color(255, 255, 255));
        navKaryawan.setText("Karyawan");
        navKaryawan.setBorder(null);
        navKaryawan.setBorderPainted(false);
        navKaryawan.setContentAreaFilled(false);
        navKaryawan.setFocusPainted(false);
        navKaryawan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        navKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navKaryawanActionPerformed(evt);
            }
        });

        navProyek.setBackground(new java.awt.Color(51, 102, 255));
        navProyek.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        navProyek.setForeground(new java.awt.Color(255, 255, 255));
        navProyek.setText("Proyek");
        navProyek.setBorder(null);
        navProyek.setBorderPainted(false);
        navProyek.setContentAreaFilled(false);
        navProyek.setFocusPainted(false);
        navProyek.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        navProyek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navProyekActionPerformed(evt);
            }
        });

        navTransaksi.setBackground(new java.awt.Color(51, 102, 255));
        navTransaksi.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        navTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        navTransaksi.setText("Transaksi");
        navTransaksi.setBorder(null);
        navTransaksi.setBorderPainted(false);
        navTransaksi.setContentAreaFilled(false);
        navTransaksi.setFocusPainted(false);
        navTransaksi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        navTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navTransaksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(navKaryawan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(navProyek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(navTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(navKaryawan)
                .addGap(18, 18, 18)
                .addComponent(navProyek)
                .addGap(18, 18, 18)
                .addComponent(navTransaksi)
                .addContainerGap(339, Short.MAX_VALUE))
        );

        Konten.add(jPanel1);

        KontenUtama.setLayout(new java.awt.CardLayout());

        KaryawanPanel.setBackground(new java.awt.Color(237, 237, 237));
        KaryawanPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FormKaryawanFrame.setBackground(new java.awt.Color(255, 255, 255));
        FormKaryawanFrame.setClosable(true);
        FormKaryawanFrame.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        FormKaryawanFrame.setVisible(false);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Nama");

        namaKaryawan.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        namaKaryawan.setText(" ");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Jabatan");

        jabatanKaryawan.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jabatanKaryawan.setText(" ");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Departemen");

        departemenKaryawan.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        departemenKaryawan.setText(" ");

        submitKaryawan.setBackground(new java.awt.Color(51, 102, 255));
        submitKaryawan.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        submitKaryawan.setForeground(new java.awt.Color(255, 255, 255));
        submitKaryawan.setText("Simpan");
        submitKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitKaryawanActionPerformed(evt);
            }
        });

        titleFormKaryawan.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        titleFormKaryawan.setForeground(new java.awt.Color(51, 102, 255));
        titleFormKaryawan.setText(" ");

        errNamaKaryawan.setForeground(new java.awt.Color(255, 0, 0));
        errNamaKaryawan.setText(" ");

        errJabatanKaryawan.setForeground(new java.awt.Color(255, 0, 0));
        errJabatanKaryawan.setText(" ");

        errDepartemenKaryawan.setForeground(new java.awt.Color(255, 0, 0));
        errDepartemenKaryawan.setText(" ");

        idFormKaryawan.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        idFormKaryawan.setForeground(new java.awt.Color(51, 102, 255));
        idFormKaryawan.setText(" ");

        javax.swing.GroupLayout FormKaryawanFrameLayout = new javax.swing.GroupLayout(FormKaryawanFrame.getContentPane());
        FormKaryawanFrame.getContentPane().setLayout(FormKaryawanFrameLayout);
        FormKaryawanFrameLayout.setHorizontalGroup(
            FormKaryawanFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormKaryawanFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FormKaryawanFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormKaryawanFrameLayout.createSequentialGroup()
                        .addComponent(titleFormKaryawan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idFormKaryawan))
                    .addGroup(FormKaryawanFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormKaryawanFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FormKaryawanFrameLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(namaKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormKaryawanFrameLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(FormKaryawanFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(errNamaKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jabatanKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(errJabatanKaryawan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormKaryawanFrameLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(FormKaryawanFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(departemenKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(errDepartemenKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(FormKaryawanFrameLayout.createSequentialGroup()
                            .addGap(236, 236, 236)
                            .addComponent(submitKaryawan))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        FormKaryawanFrameLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel4, jLabel5, jLabel6});

        FormKaryawanFrameLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {errDepartemenKaryawan, errJabatanKaryawan, errNamaKaryawan});

        FormKaryawanFrameLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {departemenKaryawan, jabatanKaryawan, namaKaryawan});

        FormKaryawanFrameLayout.setVerticalGroup(
            FormKaryawanFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormKaryawanFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FormKaryawanFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleFormKaryawan)
                    .addComponent(idFormKaryawan))
                .addGap(18, 18, 18)
                .addGroup(FormKaryawanFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(namaKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errNamaKaryawan)
                .addGap(3, 3, 3)
                .addGroup(FormKaryawanFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jabatanKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(errJabatanKaryawan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormKaryawanFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(departemenKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errDepartemenKaryawan)
                .addGap(5, 5, 5)
                .addComponent(submitKaryawan)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        FormKaryawanFrameLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel4, jLabel5, jLabel6});

        FormKaryawanFrameLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {departemenKaryawan, jabatanKaryawan, namaKaryawan});

        FormKaryawanFrameLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {errDepartemenKaryawan, errJabatanKaryawan, errNamaKaryawan});

        KaryawanPanel.add(FormKaryawanFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 340, 280));

        tbl_Karyawan.setBackground(new java.awt.Color(255, 255, 255));
        tbl_Karyawan.setForeground(new java.awt.Color(51, 51, 51));
        tbl_Karyawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama", "Jabatan", "Departemen", "", ""
            }
        ));
        tbl_Karyawan.setRowSelectionAllowed(false);
        tbl_Karyawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_KaryawanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Karyawan);

        KaryawanPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 760, 350));

        btn_addKaryawan.setBackground(new java.awt.Color(51, 102, 255));
        btn_addKaryawan.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btn_addKaryawan.setForeground(new java.awt.Color(255, 255, 255));
        btn_addKaryawan.setText("Tambah");
        btn_addKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addKaryawanActionPerformed(evt);
            }
        });
        KaryawanPanel.add(btn_addKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Data Karyawan");
        KaryawanPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        KontenUtama.add(KaryawanPanel, "card2");

        ProyekPanel.setBackground(new java.awt.Color(237, 237, 237));
        ProyekPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FormProyekFrame.setBackground(new java.awt.Color(255, 255, 255));
        FormProyekFrame.setClosable(true);
        FormProyekFrame.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        FormProyekFrame.setVisible(false);

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Nama");

        namaProyek.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        namaProyek.setText(" ");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Jabatan");

        durasiPengerjaan.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        durasiPengerjaan.setText(" ");

        submitProyek.setBackground(new java.awt.Color(51, 102, 255));
        submitProyek.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        submitProyek.setForeground(new java.awt.Color(255, 255, 255));
        submitProyek.setText("Simpan");
        submitProyek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitProyekActionPerformed(evt);
            }
        });

        titleFormProyek.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        titleFormProyek.setForeground(new java.awt.Color(51, 102, 255));
        titleFormProyek.setText(" ");

        errNamaProyek.setForeground(new java.awt.Color(255, 0, 0));
        errNamaProyek.setText(" ");

        errDurasiPengerjaan.setForeground(new java.awt.Color(255, 0, 0));
        errDurasiPengerjaan.setText(" ");

        idFormProyek.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        idFormProyek.setForeground(new java.awt.Color(51, 102, 255));
        idFormProyek.setText(" ");

        javax.swing.GroupLayout FormProyekFrameLayout = new javax.swing.GroupLayout(FormProyekFrame.getContentPane());
        FormProyekFrame.getContentPane().setLayout(FormProyekFrameLayout);
        FormProyekFrameLayout.setHorizontalGroup(
            FormProyekFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormProyekFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FormProyekFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormProyekFrameLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(submitProyek))
                    .addGroup(FormProyekFrameLayout.createSequentialGroup()
                        .addGroup(FormProyekFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FormProyekFrameLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(namaProyek, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FormProyekFrameLayout.createSequentialGroup()
                                .addComponent(titleFormProyek)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idFormProyek))
                            .addGroup(FormProyekFrameLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(FormProyekFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(errNamaProyek, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(durasiPengerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(errDurasiPengerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 4, Short.MAX_VALUE)))
                .addContainerGap())
        );

        FormProyekFrameLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel7, jLabel8});

        FormProyekFrameLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {durasiPengerjaan, namaProyek});

        FormProyekFrameLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {errDurasiPengerjaan, errNamaProyek});

        FormProyekFrameLayout.setVerticalGroup(
            FormProyekFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormProyekFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FormProyekFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleFormProyek)
                    .addComponent(idFormProyek))
                .addGap(18, 18, 18)
                .addGroup(FormProyekFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(namaProyek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(errNamaProyek)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormProyekFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(durasiPengerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(errDurasiPengerjaan)
                .addGap(18, 18, 18)
                .addComponent(submitProyek)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        FormProyekFrameLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel7, jLabel8});

        FormProyekFrameLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {durasiPengerjaan, namaProyek});

        FormProyekFrameLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {errDurasiPengerjaan, errNamaProyek});

        ProyekPanel.add(FormProyekFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 320, 240));

        tbl_Proyek.setBackground(new java.awt.Color(255, 255, 255));
        tbl_Proyek.setForeground(new java.awt.Color(51, 51, 51));
        tbl_Proyek.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama Proyek", "Durasi Pengerjaan", "", ""
            }
        ));
        tbl_Proyek.setRowSelectionAllowed(false);
        tbl_Proyek.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ProyekMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_Proyek);

        ProyekPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 760, 350));

        btn_addProyek.setBackground(new java.awt.Color(51, 102, 255));
        btn_addProyek.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btn_addProyek.setForeground(new java.awt.Color(255, 255, 255));
        btn_addProyek.setText("Tambah");
        btn_addProyek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addProyekActionPerformed(evt);
            }
        });
        ProyekPanel.add(btn_addProyek, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Data Proyek");
        ProyekPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        KontenUtama.add(ProyekPanel, "card3");

        TransaksiPanel.setBackground(new java.awt.Color(237, 237, 237));
        TransaksiPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FormTransaksiFrame.setBackground(new java.awt.Color(255, 255, 255));
        FormTransaksiFrame.setClosable(true);
        FormTransaksiFrame.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        FormTransaksiFrame.setVisible(false);

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Nama Karyawan");

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Nama Proyek");

        submitTransaksi.setBackground(new java.awt.Color(51, 102, 255));
        submitTransaksi.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        submitTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        submitTransaksi.setText("Simpan");
        submitTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitTransaksiActionPerformed(evt);
            }
        });

        titleFormTransaksi.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        titleFormTransaksi.setForeground(new java.awt.Color(51, 102, 255));
        titleFormTransaksi.setText(" ");

        errDataKaryawan.setForeground(new java.awt.Color(255, 0, 0));
        errDataKaryawan.setText(" ");

        errDataProyek.setForeground(new java.awt.Color(255, 0, 0));
        errDataProyek.setText(" ");

        idFormTransaksi.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        idFormTransaksi.setForeground(new java.awt.Color(51, 102, 255));
        idFormTransaksi.setText(" ");

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Peran");

        PeranFormTransaksi.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        errPeran.setForeground(new java.awt.Color(255, 0, 0));
        errPeran.setText(" ");

        javax.swing.GroupLayout FormTransaksiFrameLayout = new javax.swing.GroupLayout(FormTransaksiFrame.getContentPane());
        FormTransaksiFrame.getContentPane().setLayout(FormTransaksiFrameLayout);
        FormTransaksiFrameLayout.setHorizontalGroup(
            FormTransaksiFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormTransaksiFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FormTransaksiFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormTransaksiFrameLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(FormTransaksiFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DataProyekFormTransaksi, 0, 322, Short.MAX_VALUE)
                            .addComponent(errDataProyek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(FormTransaksiFrameLayout.createSequentialGroup()
                        .addComponent(titleFormTransaksi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idFormTransaksi))
                    .addGroup(FormTransaksiFrameLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(FormTransaksiFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(errPeran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PeranFormTransaksi)))
                    .addGroup(FormTransaksiFrameLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(FormTransaksiFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DataKaryawanFormTransaksi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(errDataKaryawan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormTransaksiFrameLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(submitTransaksi)))
                .addContainerGap())
        );

        FormTransaksiFrameLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel9});

        FormTransaksiFrameLayout.setVerticalGroup(
            FormTransaksiFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormTransaksiFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FormTransaksiFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleFormTransaksi)
                    .addComponent(idFormTransaksi))
                .addGap(18, 18, 18)
                .addGroup(FormTransaksiFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(DataKaryawanFormTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(errDataKaryawan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormTransaksiFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(DataProyekFormTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errDataProyek)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormTransaksiFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PeranFormTransaksi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errPeran)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submitTransaksi)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        FormTransaksiFrameLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel9});

        FormTransaksiFrameLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {errDataKaryawan, errDataProyek, errPeran});

        TransaksiPanel.add(FormTransaksiFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 460, 290));

        tbl_Transaksi.setBackground(new java.awt.Color(255, 255, 255));
        tbl_Transaksi.setForeground(new java.awt.Color(51, 51, 51));
        tbl_Transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama Karyawan", "Nama Proyek", "Peran", "", ""
            }
        ));
        tbl_Transaksi.setRowSelectionAllowed(false);
        tbl_Transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_TransaksiMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_Transaksi);

        TransaksiPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 760, 350));

        btn_addTransaksi.setBackground(new java.awt.Color(51, 102, 255));
        btn_addTransaksi.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btn_addTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        btn_addTransaksi.setText("Tambah");
        btn_addTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addTransaksiActionPerformed(evt);
            }
        });
        TransaksiPanel.add(btn_addTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Data Transaksi");
        TransaksiPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        KontenUtama.add(TransaksiPanel, "card4");

        Konten.add(KontenUtama);

        getContentPane().add(Konten, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
//    Navigasi
    private void navKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navKaryawanActionPerformed
        ((CardLayout) KontenUtama.getLayout()).show(KontenUtama, "KaryawanPanel");
    }//GEN-LAST:event_navKaryawanActionPerformed
    private void navProyekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navProyekActionPerformed
        ((CardLayout) KontenUtama.getLayout()).show(KontenUtama, "ProyekPanel");
    }//GEN-LAST:event_navProyekActionPerformed
    private void navTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navTransaksiActionPerformed
        ((CardLayout) KontenUtama.getLayout()).show(KontenUtama, "TransaksiPanel");
    }//GEN-LAST:event_navTransaksiActionPerformed
//    Karyawan
    private void resetFormKaryawan() {
        namaKaryawan.setText("");
        jabatanKaryawan.setText("");
        departemenKaryawan.setText("");
        errNamaKaryawan.setText(" ");
        errJabatanKaryawan.setText(" ");
        errDepartemenKaryawan.setText(" ");
        titleFormKaryawan.setText("");
        idFormKaryawan.setText(" ");
    }
    private void listKaryawan() {
        List<Karyawan> karyawanList = Karyawan.getAllKaryawan();
        DefaultTableModel model = (DefaultTableModel) tbl_Karyawan.getModel();
        model.setRowCount(0);
        
        for (Karyawan karyawan : karyawanList) {            
            model.addRow(new Object[]{
                karyawan.getId(),
                karyawan.getNama(),
                karyawan.getJabatan(), 
                karyawan.getDepartemen(),
                "Edit",
                "Hapus"
            });
        }
    }
    private void btn_addKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addKaryawanActionPerformed
        resetFormKaryawan();
        FormKaryawanFrame.setVisible(true);
        titleFormKaryawan.setText("Tambah Data Karyawan");
    }//GEN-LAST:event_btn_addKaryawanActionPerformed
    private void submitKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitKaryawanActionPerformed
        String nama = namaKaryawan.getText();
        String jabatan = jabatanKaryawan.getText();
        String departemen = departemenKaryawan.getText();
//        addKaryawan
        if (titleFormKaryawan.getText().equalsIgnoreCase("Tambah Data Karyawan")) {    
            if (nama.trim().isEmpty()) {
                errNamaKaryawan.setText("Form Nama tidak boleh kosong");
            } else {
                errNamaKaryawan.setText(" ");
            }
            if (jabatan.trim().isEmpty()) {
                errJabatanKaryawan.setText("Form Jabatan tidak boleh kosong");
            } else {
                errJabatanKaryawan.setText(" ");
            }
            if (departemen.trim().isEmpty()) {
                errDepartemenKaryawan.setText("Form Departemen tidak boleh kosong");
            } else {
                errDepartemenKaryawan.setText(" ");
            }

            if (errNamaKaryawan.getText().equals(" ") && 
                errJabatanKaryawan.getText().equals(" ") && 
                errDepartemenKaryawan.getText().equals(" ")
            ) {
                boolean hasil = Karyawan.addKaryawan(nama, jabatan, departemen);
                if (hasil) {
                    FormKaryawanFrame.setVisible(false);
                    JOptionPane.showMessageDialog(null, "Berhasil menambahkan Data Karyawan", "Alert", JOptionPane.INFORMATION_MESSAGE);
                    listKaryawan();
                } else {
                    JOptionPane.showMessageDialog(null, "Gagal menambahkan Data Karyawan", "Alert", JOptionPane.ERROR_MESSAGE);
                }
            }
        } 
//        updateKaryawan
        else {
            int id = Integer.parseInt(idFormKaryawan.getText());
            if (nama.trim().isEmpty()) {
                errNamaKaryawan.setText("Form Nama tidak boleh kosong");
            } else {
                errNamaKaryawan.setText(" ");
            }
            if (jabatan.trim().isEmpty()) {
                errJabatanKaryawan.setText("Form Jabatan tidak boleh kosong");
            } else {
                errJabatanKaryawan.setText(" ");
            }
            if (departemen.trim().isEmpty()) {
                errDepartemenKaryawan.setText("Form Departemen tidak boleh kosong");
            } else {
                errDepartemenKaryawan.setText(" ");
            }

            if (errNamaKaryawan.getText().equals(" ") && 
                errJabatanKaryawan.getText().equals(" ") && 
                errDepartemenKaryawan.getText().equals(" ")
            ) {
                boolean hasil = Karyawan.updateKaryawan(id, nama, jabatan, departemen);
                if (hasil) {
                    FormKaryawanFrame.setVisible(false);
                    JOptionPane.showMessageDialog(null, "Berhasil memperbarui Data Karyawan", "Alert", JOptionPane.INFORMATION_MESSAGE);
                    listKaryawan();
                } else {
                    JOptionPane.showMessageDialog(null, "Gagal memperbarui Data Karyawan", "Alert", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_submitKaryawanActionPerformed
    private void tbl_KaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_KaryawanMouseClicked
        int row = tbl_Karyawan.rowAtPoint(evt.getPoint());
        int column = tbl_Karyawan.columnAtPoint(evt.getPoint());
        
        if (column == 4) {
            int id = (int) tbl_Karyawan.getValueAt(row, 0);
            String nama = (String) tbl_Karyawan.getValueAt(row, 1);
            String jabatan = (String) tbl_Karyawan.getValueAt(row, 2);
            String departemen = (String) tbl_Karyawan.getValueAt(row, 3);
            
            resetFormKaryawan();
            FormKaryawanFrame.setVisible(true);
            titleFormKaryawan.setText("Edit Data Karyawan ID: ");
            idFormKaryawan.setText(Integer.toString(id));
            
            namaKaryawan.setText(nama);
            jabatanKaryawan.setText(jabatan);
            departemenKaryawan.setText(departemen);
        }
        if (column == 5) {
            int id = (int) tbl_Karyawan.getValueAt(row, 0);
            
            int pilihan = JOptionPane.showConfirmDialog(null, "Anda yakin ingin menghapus data id " + id +" ?", "peringatan", JOptionPane.YES_NO_OPTION);
            if (pilihan == JOptionPane.YES_OPTION) {
                boolean hasil = Karyawan.deleteKaryawan(id);
                if (hasil) {
                    JOptionPane.showMessageDialog(null, "Berhasil menghapus Data Karyawan", "Alert", JOptionPane.INFORMATION_MESSAGE);
                    listKaryawan();
                } else {
                    JOptionPane.showMessageDialog(null, "Gagal menghapus Data Karyawan", "Alert", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_tbl_KaryawanMouseClicked
//    Proyek
    private void resetFormProyek() {
        namaProyek.setText("");
        durasiPengerjaan.setText("");
        errNamaProyek.setText(" ");
        errDurasiPengerjaan.setText(" ");
        titleFormProyek.setText("");
        idFormProyek.setText(" ");
    }
    private void listProyek() {
        List<Proyek> proyekList = Proyek.getAllProyek();
        DefaultTableModel model = (DefaultTableModel) tbl_Proyek.getModel();
        model.setRowCount(0);
        
        for (Proyek proyek : proyekList) {            
            model.addRow(new Object[]{
                proyek.getId(),
                proyek.getNama_proyek(),
                proyek.getDurasi_pengerjaan(),
                "Edit",
                "Hapus"
            });
        }
    }
    private void btn_addProyekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addProyekActionPerformed
        resetFormProyek();
        FormProyekFrame.setVisible(true);
        titleFormProyek.setText("Tambah Data Proyek");
    }//GEN-LAST:event_btn_addProyekActionPerformed
    private void submitProyekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitProyekActionPerformed
        String nama_proyek = namaProyek.getText();
        String durasi_pengerjaan = durasiPengerjaan.getText();
//        addProyek
        if (titleFormProyek.getText().equalsIgnoreCase("Tambah Data Proyek")) {    
            if (nama_proyek.trim().isEmpty()) {
                errNamaProyek.setText("Form Nama Proyek tidak boleh kosong");
            } else {
                errNamaProyek.setText(" ");
            }
            if (durasi_pengerjaan.trim().isEmpty()) {
                errDurasiPengerjaan.setText("Form Durasi Pengerjaan tidak boleh kosong");
            } else {
                errDurasiPengerjaan.setText(" ");
            }

            if (errNamaProyek.getText().equals(" ") && 
                errDurasiPengerjaan.getText().equals(" ")
            ) {
                boolean hasil = Proyek.addProyek(nama_proyek, durasi_pengerjaan);
                if (hasil) {
                    FormProyekFrame.setVisible(false);
                    JOptionPane.showMessageDialog(null, "Berhasil menambahkan Data Proyek", "Alert", JOptionPane.INFORMATION_MESSAGE);
                    listProyek();
                } else {
                    JOptionPane.showMessageDialog(null, "Gagal menambahkan Data Proyek", "Alert", JOptionPane.ERROR_MESSAGE);
                }
            }
        } 
//        updateProyek
        else {
            int id = Integer.parseInt(idFormProyek.getText());
            if (nama_proyek.trim().isEmpty()) {
                errNamaProyek.setText("Form Nama Proyek tidak boleh kosong");
            } else {
                errNamaProyek.setText(" ");
            }
            if (durasi_pengerjaan.trim().isEmpty()) {
                errDurasiPengerjaan.setText("Form Durasi Pengerjaan tidak boleh kosong");
            } else {
                errDurasiPengerjaan.setText(" ");
            }

            if (errNamaProyek.getText().equals(" ") && 
                errDurasiPengerjaan.getText().equals(" ")
            ) {
                boolean hasil = Proyek.updateProyek(id, nama_proyek, durasi_pengerjaan);
                if (hasil) {
                    FormProyekFrame.setVisible(false);
                    JOptionPane.showMessageDialog(null, "Berhasil memperbarui Data Proyek", "Alert", JOptionPane.INFORMATION_MESSAGE);
                    listProyek();
                } else {
                    JOptionPane.showMessageDialog(null, "Gagal memperbarui Data Proyek", "Alert", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_submitProyekActionPerformed
    private void tbl_ProyekMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ProyekMouseClicked
        int row = tbl_Proyek.rowAtPoint(evt.getPoint());
        int column = tbl_Proyek.columnAtPoint(evt.getPoint());
        
        if (column == 3) {
            int id = (int) tbl_Proyek.getValueAt(row, 0);
            String nama_proyek = (String) tbl_Proyek.getValueAt(row, 1);
            String durasi_pengerjaan = (String) tbl_Proyek.getValueAt(row, 2);
            
            resetFormKaryawan();
            FormProyekFrame.setVisible(true);
            titleFormProyek.setText("Edit Data Proyek ID: ");
            idFormProyek.setText(Integer.toString(id));
            
            namaProyek.setText(nama_proyek);
            durasiPengerjaan.setText(durasi_pengerjaan);
        }
        if (column == 4) {
            int id = (int) tbl_Proyek.getValueAt(row, 0);
            
            int pilihan = JOptionPane.showConfirmDialog(null, "Anda yakin ingin menghapus data id " + id +" ?", "peringatan", JOptionPane.YES_NO_OPTION);
            if (pilihan == JOptionPane.YES_OPTION) {
                boolean hasil = Proyek.deleteProyek(id);
                if (hasil) {
                    JOptionPane.showMessageDialog(null, "Berhasil menghapus Data Proyek", "Alert", JOptionPane.INFORMATION_MESSAGE);
                    listProyek();
                } else {
                    JOptionPane.showMessageDialog(null, "Gagal menghapus Data Proyek", "Alert", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_tbl_ProyekMouseClicked
//    Transaksi
    private void resetFormTransaksi() {
        errDataKaryawan.setText(" ");
        errDataProyek.setText(" ");
        titleFormProyek.setText("");
        idFormProyek.setText(" ");
    }
    private void listTransaksi() {
        List<Transaksi> transaksiList = Transaksi.getAllTransaksi();
        DefaultTableModel model = (DefaultTableModel) tbl_Transaksi.getModel();
        model.setRowCount(0);
        
        for (Transaksi transaksi : transaksiList) {  
            Karyawan karyawan = Karyawan.getKaryawan(transaksi.getId_karyawan());
            Proyek proyek = Proyek.getProyek(transaksi.getId_proyek());
            model.addRow(new Object[]{
                transaksi.getId_transaksi(),
                karyawan.getNama(),
                proyek.getNama_proyek(),
                transaksi.getPeran(),
                "Edit",
                "Hapus"
            });
        }
    }
    private void btn_addTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addTransaksiActionPerformed
        List<Karyawan> karyawanList = Karyawan.getAllKaryawan();
        DataKaryawanFormTransaksi.addItem("ID | Nama | Jabatan | Departemen ");
        for (Karyawan karyawan : karyawanList) {            
            DataKaryawanFormTransaksi.addItem(
                karyawan.getId() + " | " +
                karyawan.getNama() + " | " +
                karyawan.getJabatan()+ " | " +
                karyawan.getDepartemen()
            );
        }
        List<Proyek> proyekList = Proyek.getAllProyek();
        DataProyekFormTransaksi.addItem("ID | Nama Proyek | Durasi Perngerjaan ");
        for (Proyek proyek : proyekList) {            
            DataProyekFormTransaksi.addItem(
                proyek.getId() + " | " +
                proyek.getNama_proyek()+ " | " +
                proyek.getDurasi_pengerjaan()
            );
        }
        resetFormTransaksi();
        FormTransaksiFrame.setVisible(true);
        titleFormTransaksi.setText("Tambah Data Transaksi");
    }//GEN-LAST:event_btn_addTransaksiActionPerformed
    private void submitTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitTransaksiActionPerformed
        String peran = PeranFormTransaksi.getText();
//        addTransaksi
        if (titleFormTransaksi.getText().equalsIgnoreCase("Tambah Data Transaksi")) {    
            if (DataKaryawanFormTransaksi.getSelectedIndex() == 0) {
                errDataKaryawan.setText("Anda belum memilih data karyawan");
            } else {
                errDataKaryawan.setText(" ");
            }
            if (DataProyekFormTransaksi.getSelectedIndex() == 0) {
                errDataProyek.setText("Anda belum memilihdata proyek");
            } else {
                errDataProyek.setText(" ");
            }
            if (peran.trim().isEmpty()) {
                errPeran.setText("Form Peran tidak boleh kosong");
            } else {
                errPeran.setText(" ");
            }

            if (errDataKaryawan.getText().equals(" ") && 
                errDataProyek.getText().equals(" ") &&
                errPeran.getText().equals(" ")
            ) {
                String data_karyawan = DataKaryawanFormTransaksi.getSelectedItem().toString();
                String[] ambilIdKaryawan = data_karyawan.split("\\|");
                int id_karyawan = Integer.parseInt(ambilIdKaryawan[0].trim());
                
                String data_proyek = DataProyekFormTransaksi.getSelectedItem().toString();
                String[] ambilIdProyek = data_proyek.split("\\|");
                int id_proyek = Integer.parseInt(ambilIdProyek[0].trim());

                boolean hasil = Transaksi.addTransaksi(id_karyawan, id_proyek, peran);
                if (hasil) {
                    FormTransaksiFrame.setVisible(false);
                    JOptionPane.showMessageDialog(null, "Berhasil menambahkan Data Transaksi", "Alert", JOptionPane.INFORMATION_MESSAGE);
                    listTransaksi();
                } else {
                    JOptionPane.showMessageDialog(null, "Gagal menambahkan Data Transaksi", "Alert", JOptionPane.ERROR_MESSAGE);
                }
            }
        } 
//        updateTransaksi
        else {
            int id_transaksi = Integer.parseInt(idFormTransaksi.getText());
            if (peran.trim().isEmpty()) {
                errPeran.setText("Form Peran tidak boleh kosong");
            } else {
                errPeran.setText(" ");
            }

            if (errDataKaryawan.getText().equals(" ") && 
                errDataProyek.getText().equals(" ") &&
                errPeran.getText().equals(" ")
            ) {
                String data_karyawan = DataKaryawanFormTransaksi.getSelectedItem().toString();
                String[] ambilIdKaryawan = data_karyawan.split("\\|");
                int id_karyawan = Integer.parseInt(ambilIdKaryawan[0].trim());
                
                String data_proyek = DataProyekFormTransaksi.getSelectedItem().toString();
                String[] ambilIdProyek = data_proyek.split("\\|");
                int id_proyek = Integer.parseInt(ambilIdProyek[0].trim());
                
                boolean hasil = Transaksi.updateTransaksi(id_transaksi, id_karyawan, id_proyek, peran);
                if (hasil) {
                    FormTransaksiFrame.setVisible(false);
                    JOptionPane.showMessageDialog(null, "Berhasil memperbarui Data Transaksi", "Alert", JOptionPane.INFORMATION_MESSAGE);
                    listTransaksi();
                } else {
                    JOptionPane.showMessageDialog(null, "Gagal memperbarui Data Transaksi", "Alert", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_submitTransaksiActionPerformed
    private void tbl_TransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_TransaksiMouseClicked
        int row = tbl_Transaksi.rowAtPoint(evt.getPoint());
        int column = tbl_Transaksi.columnAtPoint(evt.getPoint());
        
        if (column == 4) {
            int id = (int) tbl_Transaksi.getValueAt(row, 0);
            String peran = (String) tbl_Transaksi.getValueAt(row, 3);
            Transaksi transaksi = Transaksi.getTransaksi(id);
            
            resetFormTransaksi();
            FormTransaksiFrame.setVisible(true);
            titleFormTransaksi.setText("Edit Data Transaksi ID: ");
            idFormTransaksi.setText(Integer.toString(id));
            
            PeranFormTransaksi.setText(peran);
            Karyawan karyawanData = Karyawan.getKaryawan(transaksi.getId_karyawan());
            List<Karyawan> karyawanList = Karyawan.getAllKaryawan();
            DataKaryawanFormTransaksi.addItem(karyawanData.getId() + " | " + karyawanData.getNama() + " | " + karyawanData.getJabatan()+ " | " + karyawanData.getDepartemen());
            for (Karyawan karyawan : karyawanList) {            
                DataKaryawanFormTransaksi.addItem(
                    karyawan.getId() + " | " +
                    karyawan.getNama() + " | " +
                    karyawan.getJabatan()+ " | " +
                    karyawan.getDepartemen()
                );
            }
            Proyek proyekData = Proyek.getProyek(transaksi.getId_proyek());
            List<Proyek> proyekList = Proyek.getAllProyek();
            DataProyekFormTransaksi.addItem(proyekData.getId() + " | " + proyekData.getNama_proyek()+ " | " + proyekData.getDurasi_pengerjaan());
            for (Proyek proyek : proyekList) {            
                DataProyekFormTransaksi.addItem(
                    proyek.getId() + " | " +
                    proyek.getNama_proyek()+ " | " +
                    proyek.getDurasi_pengerjaan()
                );
            }
            
        }
        if (column == 5) {
            int id = (int) tbl_Transaksi.getValueAt(row, 0);
            
            int pilihan = JOptionPane.showConfirmDialog(null, "Anda yakin ingin menghapus data id " + id +" ?", "peringatan", JOptionPane.YES_NO_OPTION);
            if (pilihan == JOptionPane.YES_OPTION) {
                boolean hasil = Transaksi.deleteTransaksi(id);
                if (hasil) {
                    JOptionPane.showMessageDialog(null, "Berhasil menghapus Data Transaksi", "Alert", JOptionPane.INFORMATION_MESSAGE);
                    listTransaksi();
                } else {
                    JOptionPane.showMessageDialog(null, "Gagal menghapus Data Transaksi", "Alert", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_tbl_TransaksiMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> DataKaryawanFormTransaksi;
    private javax.swing.JComboBox<String> DataProyekFormTransaksi;
    private javax.swing.JInternalFrame FormKaryawanFrame;
    private javax.swing.JInternalFrame FormProyekFrame;
    private javax.swing.JInternalFrame FormTransaksiFrame;
    private javax.swing.JPanel KaryawanPanel;
    private javax.swing.JPanel Konten;
    private javax.swing.JPanel KontenUtama;
    private javax.swing.JPanel Navbar;
    private javax.swing.JTextField PeranFormTransaksi;
    private javax.swing.JPanel ProyekPanel;
    private javax.swing.JPanel TransaksiPanel;
    private javax.swing.JButton btn_addKaryawan;
    private javax.swing.JButton btn_addProyek;
    private javax.swing.JButton btn_addTransaksi;
    private javax.swing.JTextField departemenKaryawan;
    private javax.swing.JTextField durasiPengerjaan;
    private javax.swing.JLabel errDataKaryawan;
    private javax.swing.JLabel errDataProyek;
    private javax.swing.JLabel errDepartemenKaryawan;
    private javax.swing.JLabel errDurasiPengerjaan;
    private javax.swing.JLabel errJabatanKaryawan;
    private javax.swing.JLabel errNamaKaryawan;
    private javax.swing.JLabel errNamaProyek;
    private javax.swing.JLabel errPeran;
    private javax.swing.JLabel idFormKaryawan;
    private javax.swing.JLabel idFormProyek;
    private javax.swing.JLabel idFormTransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jabatanKaryawan;
    private javax.swing.JTextField namaKaryawan;
    private javax.swing.JTextField namaProyek;
    private javax.swing.JButton navKaryawan;
    private javax.swing.JButton navProyek;
    private javax.swing.JButton navTransaksi;
    private javax.swing.JButton submitKaryawan;
    private javax.swing.JButton submitProyek;
    private javax.swing.JButton submitTransaksi;
    private javax.swing.JTable tbl_Karyawan;
    private javax.swing.JTable tbl_Proyek;
    private javax.swing.JTable tbl_Transaksi;
    private javax.swing.JLabel titleFormKaryawan;
    private javax.swing.JLabel titleFormProyek;
    private javax.swing.JLabel titleFormTransaksi;
    // End of variables declaration//GEN-END:variables
}
