
import java.awt.List;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DIKNAS
 */
public class PermainanTebakAngka extends javax.swing.JFrame {

    boolean statusGame = false;
    int angka;
    int roundGame = 10;
    ArrayList<String> scoreHistory = new ArrayList<>();
    
    public PermainanTebakAngka() {
        initComponents();
        Tebak.setEnabled(false);
        CobaTebak.setEditable(false);
        Cek.setEditable(false);
        Score.setEditable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel8 = new javax.swing.JPanel();
        TabGame = new javax.swing.JButton();
        TabScore = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Tebak = new javax.swing.JButton();
        StartOrReset = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        CobaTebak = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Cek = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Score = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        HistoriScore = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(0, 204, 204));

        TabGame.setBackground(new java.awt.Color(255, 255, 255));
        TabGame.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 11)); // NOI18N
        TabGame.setForeground(new java.awt.Color(255, 102, 0));
        TabGame.setText("Game");
        TabGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TabGameActionPerformed(evt);
            }
        });
        jPanel8.add(TabGame);

        TabScore.setBackground(new java.awt.Color(255, 255, 255));
        TabScore.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 11)); // NOI18N
        TabScore.setForeground(new java.awt.Color(255, 102, 0));
        TabScore.setText("Score");
        TabScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TabScoreActionPerformed(evt);
            }
        });
        jPanel8.add(TabScore);

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 30));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo Games.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 120));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText(" 1-100");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 210, 70));

        jLabel31.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 36)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 204, 204));
        jLabel31.setText("Game Tebak Angka");
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 370, -1));

        jLabel32.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 36)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 204, 204));
        jLabel32.setText("Dari ");
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 210, 70));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(229, 229, 229));
        jLabel8.setText("38");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 69, 85));

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(229, 229, 229));
        jLabel9.setText("65");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 69, 85));

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(229, 229, 229));
        jLabel10.setText("15");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 69, 85));

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(229, 229, 229));
        jLabel11.setText("42");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 69, 85));

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(229, 229, 229));
        jLabel12.setText("79");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 69, 85));

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 48)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(229, 229, 229));
        jLabel13.setText("27");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 69, 85));

        jLabel14.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(229, 229, 229));
        jLabel14.setText("1");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 40, 85));

        jLabel15.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 48)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(229, 229, 229));
        jLabel15.setText("74");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 69, 85));

        jLabel16.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 48)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(229, 229, 229));
        jLabel16.setText("84");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 69, 85));

        jLabel17.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 48)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(229, 229, 229));
        jLabel17.setText("100");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 110, 85));

        jLabel18.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 48)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(229, 229, 229));
        jLabel18.setText("6");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 40, 85));

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(0, 204, 204));

        Tebak.setBackground(new java.awt.Color(255, 255, 255));
        Tebak.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 14)); // NOI18N
        Tebak.setForeground(new java.awt.Color(255, 102, 0));
        Tebak.setText("Tebak(10)");
        Tebak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TebakActionPerformed(evt);
            }
        });
        jPanel4.add(Tebak);

        StartOrReset.setBackground(new java.awt.Color(255, 255, 255));
        StartOrReset.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 14)); // NOI18N
        StartOrReset.setForeground(new java.awt.Color(255, 102, 0));
        StartOrReset.setText("       Start       ");
        StartOrReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartOrResetActionPerformed(evt);
            }
        });
        jPanel4.add(StartOrReset);

        jPanel1.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanel5.setBackground(new java.awt.Color(255, 102, 0));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 14)); // NOI18N
        jLabel4.setText("Coba Tebak");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 30, 0, 0);
        jPanel5.add(jLabel4, gridBagConstraints);

        CobaTebak.setBackground(new java.awt.Color(255, 255, 255));
        CobaTebak.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 11)); // NOI18N
        CobaTebak.setForeground(new java.awt.Color(255, 102, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 279;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 40, 0, 96);
        jPanel5.add(CobaTebak, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 14)); // NOI18N
        jLabel5.setText("Cek");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 30, 0, 0);
        jPanel5.add(jLabel5, gridBagConstraints);

        Cek.setBackground(new java.awt.Color(255, 255, 255));
        Cek.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 11)); // NOI18N
        Cek.setForeground(new java.awt.Color(255, 102, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 279;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 40, 0, 96);
        jPanel5.add(Cek, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 14)); // NOI18N
        jLabel6.setText("Score");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 43;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 30, 0, 0);
        jPanel5.add(jLabel6, gridBagConstraints);

        Score.setBackground(new java.awt.Color(255, 255, 255));
        Score.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 11)); // NOI18N
        Score.setForeground(new java.awt.Color(255, 102, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 279;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 40, 29, 96);
        jPanel5.add(Score, gridBagConstraints);

        jPanel1.add(jPanel5, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Home", jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 0));
        jLabel7.setText(" Score   ");
        jPanel6.add(jLabel7);

        jPanel2.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jPanel7.setBackground(new java.awt.Color(255, 102, 0));

        HistoriScore.setBackground(new java.awt.Color(255, 255, 255));
        HistoriScore.setColumns(20);
        HistoriScore.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 11)); // NOI18N
        HistoriScore.setForeground(new java.awt.Color(255, 102, 0));
        HistoriScore.setRows(5);
        jScrollPane1.setViewportView(HistoriScore);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jPanel2.add(jPanel7, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Score", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 0, 530, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartOrResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartOrResetActionPerformed
        if (statusGame) {
            reset();
        } else {
            statusGame = true;
            Tebak.setEnabled(true);
            CobaTebak.setEditable(true);
            StartOrReset.setText("Reset");
        }
        
        Random random = new Random();
        angka = random.nextInt(100); 
    }//GEN-LAST:event_StartOrResetActionPerformed
    public  void reset() {
        statusGame = false;
        Tebak.setEnabled(false);
        CobaTebak.setEditable(false);
        StartOrReset.setText("Start");
        Cek.setText("");
        Score.setText("");
        CobaTebak.setText("");
        roundGame = 10;
        Tebak.setText("tebak(" + roundGame + ")");
    }
    private void TebakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TebakActionPerformed
        try {
            if (roundGame <= 0) {
                JOptionPane.showMessageDialog(
                    null, 
                    "Anda Kalah", 
                    "You LOSE", 
                    JOptionPane.INFORMATION_MESSAGE);
                    String nama = null;
                    while (nama == null || nama.trim().isEmpty()) {
                        nama = JOptionPane.showInputDialog(null, "Masukkan Nama:", "Input Nama", JOptionPane.INFORMATION_MESSAGE);
                        if (nama == null || nama.trim().isEmpty()) {
                            JOptionPane.showMessageDialog(
                                null,
                                "Inputkan Nama",
                                "You WIN",
                                JOptionPane.WARNING_MESSAGE);
                        }
                    }
                    jTabbedPane1.setSelectedIndex(1);
                    scoreHistory.add(nama + ": 0");
                    HistoriScore.setText("");
                    for (String entry : scoreHistory) {
                        HistoriScore.append(entry + "\n"); // Tampilkan setiap entri dari List ke area teks
                    }
                    reset();
            } else {
                if (CobaTebak.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(
                        null, 
                        "Anda Belum Menebak, Silakan isi Form Coba Tebak", 
                        "Warning", 
                        JOptionPane.WARNING_MESSAGE);
                } else {
                    int cobaTebak = Integer.parseInt(CobaTebak.getText());
                    if (cobaTebak == angka) {
                        Cek.setText("Aku adalah angka " + angka);
                        int HasilScore = roundGame * 10; 
                        Score.setText(Integer.toString(HasilScore));
                        String nama = null;
                        while (nama == null || nama.trim().isEmpty()) {
                            nama = JOptionPane.showInputDialog(null, "Masukkan Nama:", "Input Nama", JOptionPane.INFORMATION_MESSAGE);
                            if (nama == null || nama.trim().isEmpty()) {
                                JOptionPane.showMessageDialog(
                                    null,
                                    "Inputkan Nama",
                                    "You WIN",
                                    JOptionPane.WARNING_MESSAGE);
                            }
                        }
                        jTabbedPane1.setSelectedIndex(1);
                        scoreHistory.add(nama + ": " + HasilScore);
                        HistoriScore.setText("");
                        for (String entry : scoreHistory) {
                            HistoriScore.append(entry + "\n"); // Tampilkan setiap entri dari List ke area teks
                        }
                        reset();
                    }
                    if (cobaTebak > angka) {
                        Cek.setText("Kebesaran");
                        roundGame--;
                        Tebak.setText("tebak(" + roundGame + ")");
                    }
                    if (cobaTebak < angka) {
                        Cek.setText("Kekecilan");
                        roundGame--;
                        Tebak.setText("tebak(" + roundGame + ")");
                    }
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                    null, 
                    "Masukkan Angka Bang", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_TebakActionPerformed

    private void TabGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TabGameActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_TabGameActionPerformed

    private void TabScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TabScoreActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_TabScoreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PermainanTebakAngka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PermainanTebakAngka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PermainanTebakAngka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PermainanTebakAngka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PermainanTebakAngka().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cek;
    private javax.swing.JTextField CobaTebak;
    private javax.swing.JTextArea HistoriScore;
    private javax.swing.JTextField Score;
    private javax.swing.JButton StartOrReset;
    private javax.swing.JButton TabGame;
    private javax.swing.JButton TabScore;
    private javax.swing.JButton Tebak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
